# This defines a workflow to make a release build of the aptos node.
# In order to trigger it go to the Actions Tab of the Repo, click "Build Aptos Node Binaries" and then "Run Workflow".

name: "Build Aptos Node Binaries"

on:
  pull_request:
    paths:
      - ".github/workflows/build-node-binaries.yaml"
  workflow_dispatch:
    inputs:
      git_ref:
        type: string
        required: true
        description: "The ref to build from i.e. aptos-node-vX.X.X"

jobs:
  build-node-binary:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    name: "Build Aptos Node Binary on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          # ref: ${{ github.event.inputs.git_ref }}
          ref: aptos-node-v1.4.3
      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@2d1ae23638b5f40a5cf29d921a158a6e978271ed # main
      - name: Build Aptos Node Binary ${{ matrix.os }}
        run: |
          set -eux

          OS="${{ matrix.os }}"
          SANITIZED_OS="${OS//./-}"
          TARNAME="aptos-node-$SANITIZED_OS.tgz"

          cargo build -p aptos-node --release
          cd target/release
          tar czvf "$TARNAME" aptos-node
          mv "$TARNAME" ../../

      - name: Upload Binary
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # pin@v3
        with:
          name: aptos-node-${{ matrix.os }}
          path: aptos-node-*.tgz