name: "Check SDK examples"
on:
  pull_request:
  push:
    branches:
      - devnet

jobs:
  # Run the TS SDK examples. Note: There are small windows where these examples
  # might be able to fail. For example, if we released a new devnet and SDK with
  # an incompatible change, but haven't updated the examples to use the new SDK.
  # That's why this is a separate job, because there are times when it could fail,
  # whereas there is no reason why the test-sdk-confirm-client-generated-publish
  # job should fail. These could also fail because we run them against devnet,
  # whereas we run the test-sdk-confirm-client-generated-publish against a node
  # built from the same commit and run as part of that CI job.
  run-examples:
    runs-on: ubuntu-latest
    env:
      APTOS_NODE_URL: https://fullnode.devnet.aptoslabs.com
      APTOS_FAUCET_URL: https://faucet.devnet.aptoslabs.com
      FAUCET_AUTH_TOKEN: ${{ secrets.DEVNET_TAP_AUTH_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: .node-version
      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4

      # Run example code in typescript.
      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: ts-example-test
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./ecosystem/typescript/sdk/examples/typescript && pnpm install && pnpm test

      # Run example code in javascript.
      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: js-example-test
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./ecosystem/typescript/sdk/examples/javascript && pnpm install && pnpm test

  run-python-examples:
    runs-on: ubuntu-latest
    env:
      APTOS_NODE_URL: https://fullnode.devnet.aptoslabs.com/v1
      APTOS_FAUCET_URL: https://faucet.devnet.aptoslabs.com
      FAUCET_AUTH_TOKEN: ${{ secrets.DEVNET_TAP_AUTH_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: ./.github/actions/python-setup
        with:
          pyproject_directory: ecosystem/python/sdk

      - uses: nick-fields/retry@7f8f3d9f0f62fe5925341be21c2e8314fd4f7c7c # pin@v2
        name: py-example-test
        with:
          max_attempts: 5
          timeout_minutes: 20
          command: cd ./ecosystem/python/sdk && make test && make examples
