name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  # contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/stale@5ebf00ea0e4c1561e9b43a292ed34424fb1d4578 # v6.0.1
        with:
          days-before-stale: 45
          days-before-close: 15
          operations-per-run: 500
          stale-issue-message: "This issue is stale because it has been open 45 days with no activity. Remove the `stale` label or comment - otherwise this will be closed in 15 days."
          stale-pr-message: "This issue is stale because it has been open 45 days with no activity. Remove the `stale` label, comment or push a commit - otherwise this will be closed in 15 days."
          exempt-issue-labels: stale-exempt
          exempt-pr-labels: stale-exempt
