name: "Cut Release Branch"
on: 
  workflow_dispatch:
    inputs:
      NEW_VERSION:
        required: true
        type: string
        description: The branch version to cut i.e. 1.4
      GIT_HASH:
        required: true
        type: string
        description: The git hash to use for the base of the new branch
      BRANCH_PREFIX:
        required: false
        type: string
        default: aptos-release-v
        description: The prefix to use for the branch name
      BRANCH_SUFFIX:
        required: false
        type: string
        default: 
        description: The suffix to use for the branch name if any
      
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  cut-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
      - name: Cut Release Branch
        run: |
          set -ex

          BRANCH_NAME="${{ inputs.BRANCH_PREFIX }}${{ inputs.NEW_VERSION }}${{ inputs.BRANCH_SUFFIX }}"

          git checkout ${{ inputs.GIT_HASH }}
          git checkout -b "$BRANCH_NAME"

          perl -i -pe 's/version\s*=\s*"[^"]*"/version = "${{ inputs.NEW_VERSION }}.0"/g' aptos-node/Cargo.toml

          git push origin "$BRANCH_NAME"
