# Continuously build Rosetta
name: Docker Build Rosetta

on:
  schedule:
    - cron: "0 9 * * 1" # once a week
  pull_request:
    paths:
      - ".github/workflows/docker-build-rosetta.yaml"

permissions:
  contents: read
  id-token: write #required for GCP Workload Identity federation

jobs:
  build:
    runs-on: high-perf-docker
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - uses: aptos-labs/aptos-core/.github/actions/docker-setup@2d1ae23638b5f40a5cf29d921a158a6e978271ed # main
        with:
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DOCKER_ARTIFACT_REPO: ${{ secrets.AWS_DOCKER_ARTIFACT_REPO }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}

      - name: Build rosetta
        run: GIT_REF=main docker/rosetta/docker-build-rosetta.sh
