name: Docker Update Images

on:
  workflow_dispatch:

  schedule:
    - cron: "0 9 * * 1" # once a week

  pull_request:
    paths:
      - scripts/update_docker_images.py
      - .github/workflows/docker-update-images.yaml

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.ENV_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ENV_DOCKERHUB_PASSWORD }}

      - name: Check and pin updates (if any)
        id: check_update
        run: python3 scripts/update_docker_images.py

      - name: Create Pull Request
        if: ${{ steps.check_update.outputs.NEED_UPDATE == 'True' }}
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          commit-message: "Update Docker images"
          title: "Update Docker images"
          body: "Update Docker images"
          base: main
          branch: "docker-update-images"
          delete-branch: true
          team-reviewers: |
            aptos-labs/prod-eng
            aptos-labs/security
          labels: |
            CICD:run-e2e-tests
