name: "Find Packages with undeclared feature dependencies"
on:
  workflow_dispatch:
  schedule:
    # every day at 3am PST
    - cron: "0 10 * * *"

jobs:
  find-packages-with-undeclared-feature-dependencies:
    runs-on: high-perf-docker
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@2d1ae23638b5f40a5cf29d921a158a6e978271ed # main
      - run: scripts/find-packages-with-undeclared-feature-dependencies.sh
