# This workflow runs a public fullnode using the `main` branch,
# connects the public fullnode to `devnet` and synchronizes the
# node using execution syncing to verify that nothing has been broken.

name: "fullnode-execute-devnet-main"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *" # At hour 0 and 12 - aka twice a day (UTC)

permissions:
  contents: read
  id-token: write
  actions: write #required for workflow cancellation via check-aptos-core

jobs:
  check-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: aptos-labs/aptos-core/.github/actions/check-aptos-core@2d1ae23638b5f40a5cf29d921a158a6e978271ed # main
        with:
          cancel-workflow: ${{ github.event_name == 'schedule' }} # Cancel the workflow if it is scheduled on a fork

  fullnode-execute-devnet-main:
    needs: check-repo
    uses: ./.github/workflows/run-fullnode-sync.yaml
    secrets: inherit
    with:
      TEST_NAME: fullnode-execute-devnet-main
      GIT_REF: main
      NETWORK: devnet
      BOOTSTRAPPING_MODE: ExecuteTransactionsFromGenesis
      CONTINUOUS_SYNCING_MODE: ExecuteTransactions
