name: "Gas Calibration"
on:
  pull_request:
  push:
    branches:
      - main
      - devnet
      - testnet
      - auto
      - canary

env:
  HAS_BUILDPULSE_SECRETS: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID != '' && secrets.BUILDPULSE_SECRET_ACCESS_KEY != '' }}
  HAS_DATADOG_SECRETS: ${{ secrets.DD_API_KEY != '' }}
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  run-gas-calibration:
    runs-on: high-perf-docker
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@2d1ae23638b5f40a5cf29d921a158a6e978271ed # main
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      - name: install Valgrind
        shell: bash
        run: sudo apt-get -y install valgrind
      - run: cargo run -p aptos-vm-profiling -- -r
