name: "*run module-verify reusable workflow"
on:
  # This allows the workflow to be triggered from another workflow
  workflow_call:
    inputs:
      GIT_SHA:
        required: false
        type: string
        description: The git SHA1 to test. If not specified, it will use the latest commit on main.
      # module-verify config
      BUCKET:
        required: true
        type: string
        description: The bucket to use for the backup. If not specified, it will use the default bucket.
      SUB_DIR:
        required: true
        type: string
        description: The subdirectory to use for the backup. If not specified, it will use the default subdirectory.
      BACKUP_CONFIG_TEMPLATE_PATH:
        description: "The path to the backup config template to use."
        type: string
        required: true
      # GHA job config
      RUNS_ON:
        description: "The runner to use for the job."
        type: string
        required: true
        default: "high-perf-docker-with-local-ssd"
      TIMEOUT_MINUTES:
        description: "Github job timeout in minutes"
        type: number
        required: true
        default: 720

jobs:
  module-verify:
    # if we're running on a PR, it's only for testing purposes, so we can set a shorter timeout
    timeout-minutes: ${{ inputs.TIMEOUT_MINUTES }}
    runs-on: ${{ inputs.RUNS_ON }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - uses: aptos-labs/aptos-core/.github/actions/rust-setup@2d1ae23638b5f40a5cf29d921a158a6e978271ed # main
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}

      - name: Install AWS CLI
        shell: bash
        run: |
          scripts/dev_setup.sh -b -i awscli
          echo "${HOME}/bin/" >> $GITHUB_PATH # default INSTALL_DIR to path

      - name: Build CLI binaries in release mode
        shell: bash
        run: cargo build --release -p aptos-db-tool

      - name: Run module-verify in parallel
        shell: bash
        run: testsuite/module_verify.py
        env:
          BUCKET: ${{ inputs.BUCKET }}
          SUB_DIR: ${{ inputs.SUB_DIR }}
          BACKUP_CONFIG_TEMPLATE_PATH: ${{ inputs.BACKUP_CONFIG_TEMPLATE_PATH }}
